export const aspects = [
  "Vigilance",
  "Commandement",
  "Agressivité",
  "Ruse",
  "Héroisme",
  "Infâmie",
  "Neutre",
];
export const types = [
  "Leader",
  "Base",
  "Unité",
  "Amélioration",
  "Évènement",
  "Jeton Unité",
];
export const rarities = [
  "Légendaire",
  "Rare",
  "Peu Commune",
  "Commune",
  "Spéciale",
];
export const arenas = ["Spatiale", "Terrestre"];
export const sets = [
  "Étincelle de Rébellion",
  "Ombres de la Galaxie",
  "Crépuscule de la République",
];
export const traits = [
  "Acquis",
  "Arme",
  "Armure",
  "Astuce",
  "Chasseur",
  "Chasseur De Primes",
  "Clone",
  "Condition",
  "Créature",
  "Désastre",
  "Droïde",
  "Force",
  "Frange",
  "Gambit",
  "Hutt",
  "Impérial",
  "Inné",
  "Inquisiteur",
  "Jawa",
  "Jedi",
  "Loi",
  "Mandalorien",
  "Marcheur",
  "Modification",
  "Nouvelle République",
  "Objet",
  "Officiel",
  "Pègre",
  "Plan",
  "Premier Ordre",
  "Prime",
  "Rebelle",
  "République",
  "Réserve",
  "Résistance",
  "Sabre Laser",
  "Séparatiste",
  "Sith",
  "Soldat",
  "Spectre",
  "Speeder",
  "Tactique",
  "Tank",
  "Transport",
  "Twi'lek",
  "Vaisseau Capital",
  "Véhicule",
  "Wookiee",
];

export const keywords = [
  "Aplomb",
  "Contrebande",
  "Coordination",
  "Débordement",
  "Embuscade",
  "Prime",
  "Protégée",
  "Raid",
  "Récupération",
  "Saboteur",
  "Sentinelle",
  "Valorisation",
];
