name: autofix.ci  # needed to securely identify the workflow

on:
  pull_request:
  push:
    branches: [ "master" ]
permissions:
  contents: write
  actions: write
  pull-requests: write
  checks: write

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          yarn
          yarn prettier . --write

      - uses: autofix-ci/action@551dded8c6cc8a1054039c8bc0b8b48c51dfc6ef